name: Deploy to AWS EC2
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Environment Variables
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
        run: |
          echo "$SSH_PRIVATE_KEY" > CloudBrian-kp.pem
          chmod 600 CloudBrian-kp.pem
 
      - name: Deploy to EC2
        run: |
          INSTANCE_ID="i-030e74ad4b5161aa7"
          PUBLIC_IP=184.73.213.163
          SSH_PORT=3003
 
          # Ensure you're using the correct EC2 user
            ssh -v -o StrictHostKeyChecking=no -p $SSH_PORT -i CloudBrian-kp.pem ubuntu@$PUBLIC_IP << 'EOF'
            set -e
            # Ensure the directory exists, or create it
            mkdir -p /home/ubuntu/MechanicApp
            cd /home/ubuntu/MechanicApp
            git pull origin main
            RAILS_ENV=production bundle install
            RAILS_ENV=production rails db:migrate
          EOF
 
      - name: Clean up
        run: |
          rm -f CloudBrian-kp.pem